import Link from "next/link";
import {notFound} from "next/navigation";
import {PageHeader} from "@/components/page-header";
import {getCompanyTaxDefaults} from "@/lib/services/core/company-service";
import {PrintButton} from "@/components/sales/print-button";
import {createClient} from "@/lib/supabase/server";
import {getCurrentCompanyId} from "@/lib/current-company";
import {convertQuotationToSalesOrder, updateQuotationStatus} from "../actions";

type QuotationItem={id:string;description:string;quantity:number|string;unit_price:number|string;line_discount:number|string;line_tax:number|string;line_total:number|string};
type EventRow={id:string;event_type:string;from_status:string|null;to_status:string|null;message:string|null;created_at:string};
const statusLabel:Record<string,string>={DRAFT:"Ã Â¸Â£Ã Â¹Ë†Ã Â¸Â²Ã Â¸â€¡",SENT:"Ã Â¸ÂªÃ Â¹Ë†Ã Â¸â€¡Ã Â¹ÂÃ Â¸Â¥Ã Â¹â€°Ã Â¸Â§",ACCEPTED:"Ã Â¸Â­Ã Â¸â„¢Ã Â¸Â¸Ã Â¸Â¡Ã Â¸Â±Ã Â¸â€¢Ã Â¸Â´",REJECTED:"Ã Â¸â€ºÃ Â¸ÂÃ Â¸Â´Ã Â¹â‚¬Ã Â¸ÂªÃ Â¸Ëœ",CANCELLED:"Ã Â¸Â¢Ã Â¸ÂÃ Â¹â‚¬Ã Â¸Â¥Ã Â¸Â´Ã Â¸Â"};
export default async function Page({params}:{params:Promise<{id:string}>}){
 const {id}=await params,s=await createClient(),companyId=await getCurrentCompanyId(),taxDefaults=await getCompanyTaxDefaults();
 const showVat=taxDefaults.is_vat_registered;
 const {data:q}=await s.from("sales_quotations").select("*,customers(*)").eq("id",id).eq("company_id",companyId).maybeSingle(); if(!q) notFound();
 const {data:items=[]}=await s.from("sales_quotation_items").select("*").eq("quotation_id",id).order("sort_order");
 const {data:events=[]}=await s.from("sales_quotation_events").select("*").eq("quotation_id",id).order("created_at",{ascending:false});
 return <div className="print:bg-white"><PageHeader eyebrow="QUOTATION" title={q.document_no} description={`${q.customers?.name||""} Ã¢â‚¬Â¢ ${q.quotation_date}`}/>
 <div className="action-row my-6 print:hidden"><Link className="btn-secondary" href="/sales/quotations">Ã¢â€ Â Ã Â¸ÂÃ Â¸Â¥Ã Â¸Â±Ã Â¸Å¡Ã Â¸Â£Ã Â¸Â²Ã Â¸Â¢Ã Â¸ÂÃ Â¸Â²Ã Â¸Â£</Link><PrintButton/>{["DRAFT","SENT","ACCEPTED","REJECTED","CANCELLED"].map(st=><form action={updateQuotationStatus} key={st}><input type="hidden" name="id" value={id}/><input type="hidden" name="status" value={st}/><button className={q.status===st?"btn-primary":"btn-secondary"}>{statusLabel[st]}</button></form>)}{q.status==="ACCEPTED"&&<form action={convertQuotationToSalesOrder} className="flex gap-2"><input type="hidden" name="quotation_id" value={id}/><input className="input" type="date" name="order_date" defaultValue={new Date().toISOString().slice(0,10)} required/><button className="btn-primary">Create SO</button></form>}</div>
 <div className="grid gap-6 xl:grid-cols-[1fr_320px]"><section className="card p-5 print:border-0 print:shadow-none"><div className="mb-7 flex items-start justify-between gap-4"><div><p className="text-2xl font-black"><span className="text-orange-600">VTN</span> Business</p><p className="text-sm text-gray-500">Ã Â¹Æ’Ã Â¸Å¡Ã Â¹â‚¬Ã Â¸ÂªÃ Â¸â„¢Ã Â¸Â­Ã Â¸Â£Ã Â¸Â²Ã Â¸â€žÃ Â¸Â² / Quotation</p></div><div className="text-right"><p className="text-xl font-black">{q.document_no}</p><p className="text-sm text-gray-500">Ã Â¸ÂªÃ Â¸â€“Ã Â¸Â²Ã Â¸â„¢Ã Â¸Â°: {statusLabel[q.status]||q.status}</p></div></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-sm text-gray-500">Ã Â¸Â¥Ã Â¸Â¹Ã Â¸ÂÃ Â¸â€žÃ Â¹â€°Ã Â¸Â²</p><p className="font-bold">{q.customers?.name}</p></div><div><p className="text-sm text-gray-500">Ã Â¸Â§Ã Â¸Â±Ã Â¸â„¢Ã Â¸â€”Ã Â¸ÂµÃ Â¹Ë†</p><p className="font-bold">{q.quotation_date}</p></div><div><p className="text-sm text-gray-500">Ã Â¹Æ’Ã Â¸Å Ã Â¹â€°Ã Â¹â€žÃ Â¸â€Ã Â¹â€°Ã Â¸â€“Ã Â¸Â¶Ã Â¸â€¡</p><p className="font-bold">{q.valid_until||"-"}</p></div><div><p className="text-sm text-gray-500">Ã Â¸ÂªÃ Â¸ÂÃ Â¸Â¸Ã Â¸Â¥Ã Â¹â‚¬Ã Â¸â€¡Ã Â¸Â´Ã Â¸â„¢</p><p className="font-bold">{q.currency_code||"THB"}</p></div><div><p className="text-sm text-gray-500">Ã Â¸Å¾Ã Â¸â„¢Ã Â¸Â±Ã Â¸ÂÃ Â¸â€¡Ã Â¸Â²Ã Â¸â„¢Ã Â¸â€šÃ Â¸Â²Ã Â¸Â¢</p><p className="font-bold">{q.salesperson||"-"}</p></div><div><p className="text-sm text-gray-500">Ã Â¹â€šÃ Â¸â€žÃ Â¸Â£Ã Â¸â€¡Ã Â¸ÂÃ Â¸Â²Ã Â¸Â£</p><p className="font-bold">{q.project_name||"-"}</p></div><div className="sm:col-span-2"><p className="text-sm text-gray-500">Ã Â¹â‚¬Ã Â¸â€¡Ã Â¸Â·Ã Â¹Ë†Ã Â¸Â­Ã Â¸â„¢Ã Â¹â€žÃ Â¸â€šÃ Â¸Å Ã Â¸Â³Ã Â¸Â£Ã Â¸Â°</p><p className="font-bold">{q.payment_terms||"-"}</p></div></div>
 <div className="table-wrap mt-6"><table className="data-table"><thead><tr><th>Ã Â¸Â£Ã Â¸Â²Ã Â¸Â¢Ã Â¸Â¥Ã Â¸Â°Ã Â¹â‚¬Ã Â¸Â­Ã Â¸ÂµÃ Â¸Â¢Ã Â¸â€</th><th>Ã Â¸Ë†Ã Â¸Â³Ã Â¸â„¢Ã Â¸Â§Ã Â¸â„¢</th><th>Ã Â¸Â£Ã Â¸Â²Ã Â¸â€žÃ Â¸Â²</th><th>Ã Â¸ÂªÃ Â¹Ë†Ã Â¸Â§Ã Â¸â„¢Ã Â¸Â¥Ã Â¸â€</th><th>Ã Â¸Â Ã Â¸Â²Ã Â¸Â©Ã Â¸Âµ</th><th>Ã Â¸Â£Ã Â¸Â§Ã Â¸Â¡</th></tr></thead><tbody>{(items as QuotationItem[] | null)?.map((x)=><tr key={x.id}><td>{x.description}</td><td>{x.quantity}</td><td>{Number(x.unit_price).toLocaleString()}</td><td>{Number(x.line_discount).toLocaleString()}</td>{showVat&&<td>{Number(x.line_tax).toLocaleString()}</td>}<td className="font-bold">{Number(x.line_total).toLocaleString()}</td></tr>)}</tbody></table></div>
 <div className="ml-auto mt-6 max-w-sm space-y-2 text-right"><p>Ã Â¸Â¢Ã Â¸Â­Ã Â¸â€Ã Â¸ÂÃ Â¹Ë†Ã Â¸Â­Ã Â¸â„¢Ã Â¸Â¥Ã Â¸â€: Ã Â¸Â¿{Number(q.subtotal).toLocaleString("th-TH",{minimumFractionDigits:2})}</p><p>Ã Â¸ÂªÃ Â¹Ë†Ã Â¸Â§Ã Â¸â„¢Ã Â¸Â¥Ã Â¸â€: Ã Â¸Â¿{Number(q.discount_amount).toLocaleString("th-TH",{minimumFractionDigits:2})}</p><p>Ã Â¸Â Ã Â¸Â²Ã Â¸Â©Ã Â¸Âµ: Ã Â¸Â¿{Number(q.tax_amount).toLocaleString("th-TH",{minimumFractionDigits:2})}</p><p className="text-2xl font-black">Ã Â¸Â£Ã Â¸Â§Ã Â¸Â¡ Ã Â¸Â¿{Number(q.total_amount).toLocaleString("th-TH",{minimumFractionDigits:2})}</p></div>{q.notes&&<div className="mt-6 rounded-xl bg-gray-50 p-4"><p className="text-xs font-bold text-gray-500">Ã Â¸Â«Ã Â¸Â¡Ã Â¸Â²Ã Â¸Â¢Ã Â¹â‚¬Ã Â¸Â«Ã Â¸â€¢Ã Â¸Â¸</p><p className="mt-1">{q.notes}</p></div>}</section>
 <aside className="card p-5 print:hidden"><h2 className="font-black">Timeline Ã Â¹â‚¬Ã Â¸Â­Ã Â¸ÂÃ Â¸ÂªÃ Â¸Â²Ã Â¸Â£</h2><div className="mt-5 space-y-5">{(events as EventRow[]|null)?.map(e=><div key={e.id} className="relative border-l-2 border-orange-200 pl-4"><span className="absolute -left-[7px] top-1 h-3 w-3 rounded-full bg-orange-500"/><p className="font-bold">{e.message||e.event_type}</p><p className="mt-1 text-xs text-gray-500">{new Date(e.created_at).toLocaleString("th-TH")}</p></div>)}{!events?.length&&<p className="text-sm text-gray-500">Ã Â¸Â¢Ã Â¸Â±Ã Â¸â€¡Ã Â¹â€žÃ Â¸Â¡Ã Â¹Ë†Ã Â¸Â¡Ã Â¸ÂµÃ Â¸â€ºÃ Â¸Â£Ã Â¸Â°Ã Â¸Â§Ã Â¸Â±Ã Â¸â€¢Ã Â¸Â´</p>}</div></aside></div></div>
}
