import Link from "next/link";
import {notFound} from "next/navigation";
import {PageHeader} from "@/components/page-header";
import {PrintButton} from "@/components/sales/print-button";
import {createClient} from "@/lib/supabase/server";
import {getCurrentCompanyId} from "@/lib/current-company";
import {convertQuotationToSalesOrder, updateQuotationStatus} from "../actions";

type QuotationItem={id:string;description:string;quantity:number|string;unit_price:number|string;line_discount:number|string;line_tax:number|string;line_total:number|string};
type EventRow={id:string;event_type:string;from_status:string|null;to_status:string|null;message:string|null;created_at:string};
const statusLabel:Record<string,string>={DRAFT:"ร่าง",SENT:"ส่งแล้ว",ACCEPTED:"อนุมัติ",REJECTED:"ปฏิเสธ",CANCELLED:"ยกเลิก"};
export default async function Page({params}:{params:Promise<{id:string}>}){
 const {id}=await params,s=await createClient(),companyId=await getCurrentCompanyId();
 const {data:q}=await s.from("sales_quotations").select("*,customers(*)").eq("id",id).eq("company_id",companyId).maybeSingle(); if(!q) notFound();
 const {data:items=[]}=await s.from("sales_quotation_items").select("*").eq("quotation_id",id).order("sort_order");
 const {data:events=[]}=await s.from("sales_quotation_events").select("*").eq("quotation_id",id).order("created_at",{ascending:false});
 return <div className="print:bg-white"><PageHeader eyebrow="QUOTATION" title={q.document_no} description={`${q.customers?.name||""} • ${q.quotation_date}`}/>
 <div className="action-row my-6 print:hidden"><Link className="btn-secondary" href="/sales/quotations">← กลับรายการ</Link><PrintButton/>{["DRAFT","SENT","ACCEPTED","REJECTED","CANCELLED"].map(st=><form action={updateQuotationStatus} key={st}><input type="hidden" name="id" value={id}/><input type="hidden" name="status" value={st}/><button className={q.status===st?"btn-primary":"btn-secondary"}>{statusLabel[st]}</button></form>)}{q.status==="ACCEPTED"&&<form action={convertQuotationToSalesOrder} className="flex gap-2"><input type="hidden" name="quotation_id" value={id}/><input className="input" type="date" name="order_date" defaultValue={new Date().toISOString().slice(0,10)} required/><button className="btn-primary">Create SO</button></form>}</div>
 <div className="grid gap-6 xl:grid-cols-[1fr_320px]"><section className="card p-5 print:border-0 print:shadow-none"><div className="mb-7 flex items-start justify-between gap-4"><div><p className="text-2xl font-black"><span className="text-orange-600">VTN</span> Business</p><p className="text-sm text-gray-500">ใบเสนอราคา / Quotation</p></div><div className="text-right"><p className="text-xl font-black">{q.document_no}</p><p className="text-sm text-gray-500">สถานะ: {statusLabel[q.status]||q.status}</p></div></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-sm text-gray-500">ลูกค้า</p><p className="font-bold">{q.customers?.name}</p></div><div><p className="text-sm text-gray-500">วันที่</p><p className="font-bold">{q.quotation_date}</p></div><div><p className="text-sm text-gray-500">ใช้ได้ถึง</p><p className="font-bold">{q.valid_until||"-"}</p></div><div><p className="text-sm text-gray-500">สกุลเงิน</p><p className="font-bold">{q.currency_code||"THB"}</p></div><div><p className="text-sm text-gray-500">พนักงานขาย</p><p className="font-bold">{q.salesperson||"-"}</p></div><div><p className="text-sm text-gray-500">โครงการ</p><p className="font-bold">{q.project_name||"-"}</p></div><div className="sm:col-span-2"><p className="text-sm text-gray-500">เงื่อนไขชำระ</p><p className="font-bold">{q.payment_terms||"-"}</p></div></div>
 <div className="table-wrap mt-6"><table className="data-table"><thead><tr><th>รายละเอียด</th><th>จำนวน</th><th>ราคา</th><th>ส่วนลด</th><th>ภาษี</th><th>รวม</th></tr></thead><tbody>{(items as QuotationItem[] | null)?.map((x)=><tr key={x.id}><td>{x.description}</td><td>{x.quantity}</td><td>{Number(x.unit_price).toLocaleString()}</td><td>{Number(x.line_discount).toLocaleString()}</td><td>{Number(x.line_tax).toLocaleString()}</td><td className="font-bold">{Number(x.line_total).toLocaleString()}</td></tr>)}</tbody></table></div>
 <div className="ml-auto mt-6 max-w-sm space-y-2 text-right"><p>ยอดก่อนลด: ฿{Number(q.subtotal).toLocaleString("th-TH",{minimumFractionDigits:2})}</p><p>ส่วนลด: ฿{Number(q.discount_amount).toLocaleString("th-TH",{minimumFractionDigits:2})}</p><p>ภาษี: ฿{Number(q.tax_amount).toLocaleString("th-TH",{minimumFractionDigits:2})}</p><p className="text-2xl font-black">รวม ฿{Number(q.total_amount).toLocaleString("th-TH",{minimumFractionDigits:2})}</p></div>{q.notes&&<div className="mt-6 rounded-xl bg-gray-50 p-4"><p className="text-xs font-bold text-gray-500">หมายเหตุ</p><p className="mt-1">{q.notes}</p></div>}</section>
 <aside className="card p-5 print:hidden"><h2 className="font-black">Timeline เอกสาร</h2><div className="mt-5 space-y-5">{(events as EventRow[]|null)?.map(e=><div key={e.id} className="relative border-l-2 border-orange-200 pl-4"><span className="absolute -left-[7px] top-1 h-3 w-3 rounded-full bg-orange-500"/><p className="font-bold">{e.message||e.event_type}</p><p className="mt-1 text-xs text-gray-500">{new Date(e.created_at).toLocaleString("th-TH")}</p></div>)}{!events?.length&&<p className="text-sm text-gray-500">ยังไม่มีประวัติ</p>}</div></aside></div></div>
}
