"use client";
import {useMemo,useState} from "react";

type Customer={id:string;code:string;name:string}; type Product={id:string;sku:string;name:string;selling_price:number};
type Item={product_id:string;description:string;quantity:number;unit_price:number;discount_percent:number;tax_rate:number};
export function QuotationForm({customers,products,action}:{customers:Customer[];products:Product[];action:(fd:FormData)=>void}){
 const [items,setItems]=useState<Item[]>([{product_id:"",description:"",quantity:1,unit_price:0,discount_percent:0,tax_rate:7}]);
 const sum=useMemo(()=>items.reduce((a,x)=>{const s=x.quantity*x.unit_price,d=s*x.discount_percent/100,t=(s-d)*x.tax_rate/100;return a+s-d+t},0),[items]);
 const patch=(i:number,p:Partial<Item>)=>setItems(v=>v.map((x,n)=>n===i?{...x,...p}:x));
 return <form action={action} className="card p-5 space-y-5"><input type="hidden" name="items" value={JSON.stringify(items)}/>
  <div className="form-grid"><label><span className="label">ลูกค้า *</span><select className="input" name="customer_id" required defaultValue=""><option value="" disabled>เลือกลูกค้า</option>{customers.map(x=><option key={x.id} value={x.id}>{x.code} - {x.name}</option>)}</select></label><label><span className="label">วันที่ใบเสนอราคา *</span><input className="input" type="date" name="quotation_date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label><span className="label">ใช้ได้ถึง</span><input className="input" type="date" name="valid_until"/></label><label className="full"><span className="label">หมายเหตุ</span><textarea className="input textarea" name="notes"/></label></div>
  <div className="table-wrap"><table className="data-table"><thead><tr><th>สินค้า</th><th>รายละเอียด</th><th>จำนวน</th><th>ราคา</th><th>ส่วนลด %</th><th>VAT %</th><th></th></tr></thead><tbody>{items.map((x,i)=><tr key={i}><td><select className="input" value={x.product_id} onChange={e=>{const p=products.find(z=>z.id===e.target.value);patch(i,{product_id:e.target.value,description:p?.name||"",unit_price:Number(p?.selling_price||0)})}}><option value="">ไม่ผูกสินค้า</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} - {p.name}</option>)}</select></td><td><input className="input" value={x.description} onChange={e=>patch(i,{description:e.target.value})}/></td><td><input className="input" type="number" min="0.0001" step="0.0001" value={x.quantity} onChange={e=>patch(i,{quantity:Number(e.target.value)})}/></td><td><input className="input" type="number" min="0" step="0.01" value={x.unit_price} onChange={e=>patch(i,{unit_price:Number(e.target.value)})}/></td><td><input className="input" type="number" min="0" max="100" step="0.01" value={x.discount_percent} onChange={e=>patch(i,{discount_percent:Number(e.target.value)})}/></td><td><input className="input" type="number" min="0" step="0.01" value={x.tax_rate} onChange={e=>patch(i,{tax_rate:Number(e.target.value)})}/></td><td><button type="button" className="btn-secondary btn-small" onClick={()=>setItems(v=>v.filter((_,n)=>n!==i))} disabled={items.length===1}>ลบ</button></td></tr>)}</tbody></table></div>
  <div className="flex flex-wrap items-center justify-between gap-3"><button type="button" className="btn-secondary" onClick={()=>setItems(v=>[...v,{product_id:"",description:"",quantity:1,unit_price:0,discount_percent:0,tax_rate:7}])}>+ เพิ่มรายการ</button><div className="text-right"><p className="text-sm text-gray-500">ยอดรวมโดยประมาณ</p><p className="text-2xl font-black">฿{sum.toLocaleString("th-TH",{minimumFractionDigits:2})}</p></div></div>
  <div className="action-row"><button className="btn-primary">บันทึกใบเสนอราคา</button></div>
 </form>
}
